export * from './actions';
export * from './effects';
export * from './reducers';
export * from './services';

import {
  ServiceDataService,
  ServiceDispatchers,
  ServiceSelectors,
  AppointmentMetaDispatchers,
  AppointmentMetaSelectors,
  AppointmentDataService,
  AppointmentDispatchers,
  AppointmentSelectors,
  NumberOfCustomersDispatchers,
  NumberOfCustomersSelectors,
  CustomerDataService,
  CustomerDispatchers,
  CustomerSelectors,
  BranchDataService,
  BranchDispatchers,
  BranchSelectors,
  DateDataService,
  DateDispatchers,
  DateSelectors,
  TimeslotDataService,
  TimeslotDispatchers,
  TimeslotSelectors,
  SystemInfoDataService,
  SystemInfoDispatchers,
  SystemInfoSelectors,
  UserDataService,
  UserDispatchers,
  UserSelectors,
  LicenseDataService,
  LicenseDispatchers,
  LicenseInfoSelectors,
  UserRoleDataService,
  UserRoleDispatchers,
  UserRoleSelectors,
  SettingsAdminDataService,
  SettingsAdminDispatchers,
  SettingsAdminSelectors,
  ReserveDataService,
  ReserveDispatchers,
  ReserveSelectors,
  AccountDataService,
  AccountDispatchers
} from './services';

export const storeServices = [
  ServiceDataService,
  ServiceDispatchers,
  ServiceSelectors,
  AppointmentMetaDispatchers,
  AppointmentMetaSelectors,
  AppointmentDataService,
  AppointmentDispatchers,
  AppointmentSelectors,
  NumberOfCustomersDispatchers,
  NumberOfCustomersSelectors,
  CustomerDataService,
  CustomerDispatchers,
  CustomerSelectors,
  BranchDataService,
  BranchDispatchers,
  BranchSelectors,
  DateDataService,
  DateDispatchers,
  DateSelectors,
  TimeslotDataService,
  TimeslotDispatchers,
  TimeslotSelectors,
  SystemInfoDataService,
  SystemInfoDispatchers,
  SystemInfoSelectors,
  UserDataService,
  UserDispatchers,
  UserSelectors,
  LicenseDataService,
  LicenseDispatchers,
  LicenseInfoSelectors,
  UserRoleDataService,
  UserRoleDispatchers,
  UserRoleSelectors,
  SettingsAdminDataService,
  SettingsAdminDispatchers,
  SettingsAdminSelectors,
  ReserveDataService,
  ReserveDispatchers,
  ReserveSelectors,
  AccountDataService,
  AccountDispatchers
];
