import { ICustomer } from './ICustomer';
import { IBranch } from './IBranch';
import { IService } from './IService';
import { IResource } from './IResource';
import { IActionAllAppointment, IActionAppointment } from './IActionAppointment';

export interface IAppointment {
  publicId?: string;
  status?: any;
  created?: number;
  updated?: number;
  start?: string;
  startTime?: string;
  numberOfCustomers?: number;
  custom?: string;
  customers?: ICustomer[];
  branch?: IBranch;
  services?: IService[];
  title?: string;
  notes?: string;
  allDay?: boolean;
  blocking?: boolean;
  end?: string;
  endTime?: string;
  resource?: IResource;
  deleted?: boolean;
  qpId?: number;
  id?: string;
  invokeStatEvent?: boolean;
  externalNotes?: string;
  externalId?: string;
  entityId?: string;
  operation?: string;
  username?: string;
  change?: any;
  actionData?: IActionAllAppointment;
  branchId?: number;
  actionBranch?: string;
  timeStamp?: string;
  resourceName?: string;
  properties?: {notes?: string};
  updateTime?: string;
}
